/**
 * 
 * @param {string} name 
 * @returns 
 */

import key from './key'

const url = `app/${key}`
export const LOAD_RECORDS = `${url}/LOAD_RECORDS`
export const LOAD_RECORDS_SUCCESS = `${url}/LOAD_RECORDS_SUCCESS`
export const LOAD_RECORDS_ERROR = `${url}/LOAD_RECORDS_ERROR`
export const LOAD_RECORD = `${url}/LOAD_RECORD`
export const LOAD_RECORD_SUCCESS = `${url}/LOAD_RECORD_SUCCESS`
export const LOAD_RECORD_ERROR = `${url}/LOAD_RECORD_ERROR`
export const CREATE_RECORD = `${url}/CREATE_RECORD`
export const CREATE_RECORD_SUCCESS = `${url}/CREATE_RECORD_SUCCESS`
export const CREATE_RECORD_ERROR = `${url}/CREATE_RECORD_ERROR`
export const UPDATE_RECORD = `${url}/UPDATE_RECORD`
export const UPDATE_RECORD_SUCCESS = `${url}/UPDATE_RECORD_SUCCESS`
export const UPDATE_RECORD_ERROR = `${url}/UPDATE_RECORD_ERROR`
export const DELETE_RECORD = `${url}/DELETE_RECORD`
export const DELETE_RECORD_SUCCESS = `${url}/DELETE_RECORD_SUCCESS`
export const DELETE_RECORD_ERROR = `${url}/DELETE_RECORD_ERROR`
export const LOAD_RECORDS_META_DATA = `${url}/LOAD_RECORDS_META_DATA`
export const LOAD_RECORDS_META_DATA_SUCCESS = `${url}/LOAD_RECORDS_META_DATA_SUCCESS`
export const LOAD_RECORDS_META_DATA_ERROR = `${url}/LOAD_RECORDS_META_DATA_ERROR`
export const LOAD_RECORDS_VALID_CACHE = `${url}/LOAD_RECORDS_VALID_CACHE`
export const UPDATE_STATUS = `${url}/UPDATE_STATUS`
export const UPDATE_STATUS_SUCCESS = `${url}/UPDATE_STATUS_SUCCESS`
export const UPDATE_STATUS_ERROR = `${url}/UPDATE_STATUS_ERROR`
const constants = {
  LOAD_RECORDS,
  LOAD_RECORDS_SUCCESS,
  LOAD_RECORDS_ERROR,
  LOAD_RECORD,
  LOAD_RECORD_SUCCESS,
  LOAD_RECORD_ERROR,
  CREATE_RECORD,
  CREATE_RECORD_SUCCESS,
  CREATE_RECORD_ERROR,
  UPDATE_RECORD,
  UPDATE_RECORD_SUCCESS,
  UPDATE_RECORD_ERROR,
  DELETE_RECORD,
  DELETE_RECORD_SUCCESS,
  DELETE_RECORD_ERROR,
  LOAD_RECORDS_VALID_CACHE,
  LOAD_RECORDS_META_DATA,
  LOAD_RECORDS_META_DATA_SUCCESS,
  LOAD_RECORDS_META_DATA_ERROR,
  UPDATE_STATUS,
  UPDATE_STATUS_SUCCESS,
  UPDATE_STATUS_ERROR
}

export default constants
